name: furugiya_map_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.14.0
  http: ^1.6.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  google_mobile_ads: ^6.0.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  image_picker: ^1.2.1
  # ⬇️ 秘匿情報管理のために追加
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ⬇️ .envファイルをアプリ内で読み込めるように追加
  assets:
    - .env